import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Nav from '@/components/Nav'
import Hero from '@/components/Hero'
import Info from '@/components/Info'
import Card from '@/components/Card'


import {
  Box,
  Text,
  Flex
} from "@chakra-ui/react";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
    <Box 
    bgColor={"#F2F2F2"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Hero />
      <Info />
      <Box textAlign={"center"}>
        <Text
        color="#192E23"
        fontFamily="Lato"
        fontWeight={"extrabold"}
        fontSize={"2em"}>
          CASAS RURALES
        </Text>
        <Flex
        padding={"20"}
        gap={"20"}
        alignItems={{base: "center", xl: "start"}}
        direction={{base: "column", xl: "row"}}>
          <Card 
          name = {"LA CASA GRANDE 1"}
          price = {110}
          people = {8}
          link = {""}/>
          <Card 
          name = {"LA CASA GRANDE 2"}
          price = {90}
          people = {6}
          link = {""}/>
        </Flex>
      </Box>
    </Box>
    </>
  )
} 


