import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Nav from "@/components/Nav";
import Hero from "@/components/Hero";
import Info from "@/components/Info";
import Card from "@/components/Card";
import ActivityCard from "@/components/ActivityCard";

import { Box, Text, Flex } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Box bgColor={"#F2F2F2"}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Nav />
        <Hero />
        <Info />
        <Box textAlign={"center"}>
          <Text
            color="#192E23"
            fontFamily="Lato"
            fontWeight={"extrabold"}
            fontSize={"2em"}
          >
            CASAS RURALES
          </Text>
          <Flex
            padding={"20"}
            paddingTop={"10"}
            gap={"20"}
            alignItems={{ base: "center", xl: "start" }}
            justifyContent={"space-evenly"}
            direction={{ base: "column", xl: "row" }}
          >
            <Card
              name={"LA CASA GRANDE 1"}
              price={110}
              people={8}
              link={""}
              image={
                "https://www.tuscasasrurales.com/img/605x/casas-rurales.jpg"
              }
            />
            <Card
              name={"LA CASA GRANDE 2"}
              price={90}
              people={6}
              link={""}
              image={
                "https://www.ruralesdata.com/cache/alojamientos/aguirre-casa-rural/202-aguirre-casa-rural-elizondo-fachada.jpg"
              }
            />
          </Flex>
          <Text
            color="#192E23"
            fontFamily="Lato"
            fontWeight={"extrabold"}
            fontSize={"2em"}
          >
            QUÉ HACER
          </Text>
          <Flex
            padding={"20"}
            paddingTop={"10"}
            gap={"20"}
            alignItems={{ base: "center", xl: "start" }}
            justifyContent={"space-evenly"}
            direction={{ base: "column", xl: "row" }}
          >
            <ActivityCard
              name={"ENTORNO"}
              description={
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla Vulputate in felis at faucibus."
              }
              link={""}
              image={
                "https://guiadeasturias.com/wp-content/uploads/2017/11/santuario-lagos-covadonga-asturias-2.jpg"
              }
            ></ActivityCard>
            <ActivityCard
              name={"ACTIVIDADES"}
              description={
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla Vulputate in felis at faucibus."
              }
              link={""}
              image={
                "https://www.turismoasturias.es/documents/11022/90227/CARES.jpg/0520436c-748a-42ab-9e99-7703dd111d2c?t=1540901739869"
              }
            ></ActivityCard>
          </Flex>
        </Box>
      </Box>
    </>
  );
}
